[connections]
  [connections.supabase]
  url = "https://btzzynyftybhgblfhlxk.supabase.co"
  key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0enp5bnlmdHliaGdibGZobHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODQ2NTUsImV4cCI6MjA3MjE2MDY1NX0.x4_RZoOnf3vY-HWxro48lxycwhSx-gCMuhLWNCdcogk"
